import { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'EasyBank2.0',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className='antialiased'>{children}</body>
    </html>
  );
}
